{
 "title": "TIG",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RAM used in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"used_percent\") AS \"RAM used %\"\nFROM \"mem\"\nWHERE $timeFilter\nGROUP BY time(1m, now())"
    }
   ]
  },
  {
   "title": "RAM used in GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT\n  mean(\"used\")/1024/1024/1024      AS \"Used (GB)\",\n  mean(\"total\")/1024/1024/1024 AS \"Total (GB)\"\nFROM \"mem\"\nWHERE $timeFilter\nGROUP BY time(1m) fill(null)"
    }
   ]
  },
  {
   "title": "CPU usage in %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"usage_active\")\nFROM \"cpu\"\nWHERE $timeFilter AND \"cpu\" = 'cpu-total'\nGROUP BY time(1m)"
    }
   ]
  }
 ]
}